---
# Uncomment if running against azure server
#- hosts: titanawx_azure
#  remote_user: vagrant
#  roles:
#    - titan_awx

# Uncomment if running against local titanawx_focal server
- hosts: titanawx_focal
  remote_user: vagrant
  roles:
    - titan_awx

# Uncomment if running against local titan server (ansible core not awx)
#- hosts: titan
#  remote_user: vagrant
#  roles:
#    - titan
